import { Event } from './Event';
import { EventFactory } from './EventFactory';

export interface CreateEventDTO {
  organizerId: string;
  title: string;
  description: string;
  date: string;
  basePrice: number;
  capacity: number;
}

export class EventCreationController {
  
  public static async createNewEvent(data: CreateEventDTO): Promise<Event> {
    // Basic Field Validations
    if (!data.title.trim() || !data.description.trim() || !data.date.trim()) {
      throw new Error('All event configuration fields are required.');
    }

    if (data.capacity <= 0) {
      throw new Error('General admission capacity must be at least 1.');
    }

    // Price Below Gateway Minimum Rule (RM1.00 local minimum fee)
    if (data.basePrice > 0 && data.basePrice < 1.00) {
      throw new Error('Price must cover minimum RM1.00 processing fee');
    }

    try {
      // Retrieve the local IP base URL from your mobile/.env config
      const baseURL = process.env.EXPO_PUBLIC_API_URL;
      if (!baseURL) {
        throw new Error('Network configuration error: EXPO_PUBLIC_API_URL is missing.');
      }

      const SERVER_URL = `${baseURL}/api/events`;
      console.log(`[Network] Dispatching payload to: ${SERVER_URL}`);

      // Structure the payload
      const payload = {
        organizerId: data.organizerId, // Will be passed in from the UI layer
        title: data.title,
        description: data.description,
        eventDate: data.date,
        capacity: data.capacity,
        ticketPrice: data.basePrice,
      };

      // Execute network call
      const response = await fetch(SERVER_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.error || 'Server rejected event registration.');
      }

      console.log('[EventCreationController] Database sync complete:', result.message);
      
      // Return the complete event object generated by the database
      return result.event as Event;

    } catch (error: any) {
      console.error('[EventCreationController] Critical workflow failure:', error);
      throw new Error(error.message || 'Network connection failed. Verify your server is active.');
    }
  }

  public static async getPublishedEvents(): Promise<Event[]> {
    try {
      const baseURL = process.env.EXPO_PUBLIC_API_URL;
      const response = await fetch(`${baseURL}/api/events`);
      const result = await response.json();
      
      if (!response.ok) throw new Error('Failed to retrieve events');
      return result.events as Event[];
    } catch (error) {
      console.error('[EventCreationController] Failed to fetch directory:', error);
      return [];
    }
  }
}